/*
 * BarProductOverview.java
 *
 * Created on May 18, 2012, 8:54:23 PM
 */
package view.admin;

import helper.SearchTable;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import main.Application;
import model.Product;

/**
 * BarProductOverview:
 * This is the view for the Overview of the Barporducts
 * From this view it is possible to see all the barproducts and from
 * here you can go to editing and adding products.
 * 
 * @author vm
 */
public class BarProductOverview extends javax.swing.JPanel {

	private ListSelectionModel row;
	protected DefaultTableModel model;
	private final SearchTable searchTable;

	/**
	 * This is the constructor for the BarProductOverview view.
	 * Creates new form BarProductOverview
	 */
	public BarProductOverview() {
		Product product = new Product();
		initComponents();

		//Make the table searchable.
		this.searchTable = new SearchTable(jTable1, jTextFieldSearch, jButtonReset);

		this.model = (DefaultTableModel) jTable1.getModel();

		//Get the format of the objects
		product.getTableRowObjects();
		updateTable();
	}

	/**
	 * This method fills the jTable in the BarProductOverview.
	 * @author daan
	 * 
	 */
	private void updateTable() {
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		//User user = Session.get().getLoggedInUser();

		// First, empty it.
		model.setRowCount(0);

		// Secondly, fill it with all products
		ArrayList<Product> products = Product.readAll();

		for (Product product : products) {
			model.addRow(product.getTableRowObjects());
		}
	}

	/**
	 * This method will show a product which is selected in a row. The product
	 * will be shown in a different view, the view.admin.BarProductModify.java view.
	 *
	 * @author vm
	 */
	private void showProduct() {

        // Get the currently selected product
		int rowNumber = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());
		String stringId = (String) model.getValueAt(rowNumber, 0);
		int productId = Integer.parseInt(stringId);
		
		//Set the product data in the view
		Application.getInstance().showPanel(new view.admin.BarProductModify(productId));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonProductAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();

        jButtonProductAdd.setText("+");
        jButtonProductAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductAddActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Naam", "Type", "Extra", "Prijs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel1.setText("Product Overzicht");

        jTextFieldSearch.setText("Zoek...");

        jButtonReset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addComponent(jButtonProductAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProductAdd)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonProductAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductAddActionPerformed
		// Go to the view of view.admin.BarProductAdd
		Application.getInstance().showPanel(new view.admin.BarProductAdd());
	}//GEN-LAST:event_jButtonProductAddActionPerformed

	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
		// When there is a double-click do this:
		if (evt.getClickCount() >= 2) {
			// Double clicked!
			showProduct();
		}

	}//GEN-LAST:event_jTable1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonProductAdd;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
