/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CourseAdd.java
 *
 * Created on May 18, 2012, 8:53:21 PM
 */
package view.admin;

import javax.swing.ButtonGroup;
import main.Application;
import model.Subscription;
import view.popups.SuccessPopup;

/**
 * This is the view for adding a course
 * @author vm
 */
public class CourseAdd extends javax.swing.JPanel {

	String days;
	String type;
	Subscription subscription = new Subscription();

	/** Creates new form CourseAdd */
	public CourseAdd() {
		initComponents();
		selectionCheck(); // Is not so need, help anybody

		jComboBoxAgeGroup.removeAllItems();
		jComboBoxAgeGroup.addItem("< 16");
		jComboBoxAgeGroup.addItem("16 - 18");
		jComboBoxAgeGroup.addItem("18 - 65");
		jComboBoxAgeGroup.addItem("65 +");

		ButtonGroup buttongroupType = new ButtonGroup();
		buttongroupType.add(jRadioButtonCourseType1);
		buttongroupType.add(jRadioButtonCourseType2);

		ButtonGroup buttongroupGender = new ButtonGroup();
		buttongroupGender.add(jRadioButtonMale);
		buttongroupGender.add(jRadioButtonFemale);
		buttongroupGender.add(jRadioButtonMixed);

	}

	/*
	 * Check on selection of the JRadioButtonCourseType2
	 * @author vm
	 * 
	 */
	public void selectionCheck() {

		if (jRadioButtonCourseType2.isSelected()) {
			enableCheckBox();
		} else {
			disableCheckBox();
		}
	}

	public void enableCheckBox() {
		//Enable all the checkboxes
		jCheckBoxMonday.setEnabled(true);
		jCheckBoxTuesday.setEnabled(true);
		jCheckBoxWednesday.setEnabled(true);
		jCheckBoxThursday.setEnabled(true);
		jCheckBoxFriday.setEnabled(true);
		jCheckBoxSaturday.setEnabled(true);
		jCheckBoxSunday.setEnabled(true);

	}

	public void disableCheckBox() {
		//Disable all the checkboxes
		jCheckBoxMonday.setEnabled(false);
		jCheckBoxTuesday.setEnabled(false);
		jCheckBoxWednesday.setEnabled(false);
		jCheckBoxThursday.setEnabled(false);
		jCheckBoxFriday.setEnabled(false);
		jCheckBoxSaturday.setEnabled(false);
		jCheckBoxSunday.setEnabled(false);
	}

	public void getDays() {
		days = jCheckBoxMonday.getText() + " "
				+ jCheckBoxTuesday.getText() + " "
				+ jCheckBoxWednesday.getText() + " "
				+ jCheckBoxThursday.getText() + " "
				+ jCheckBoxFriday.getText() + " "
				+ jCheckBoxSaturday.getText() + " "
				+ jCheckBoxSunday.getText();

	}

	public void setSubscriptionData() {
		
			
			String name = jTextFieldCourseName.getText();
			subscription.setTitle(name);
			
			String startTime = jTextFieldStartTime.getText();
			String endTime = jTextFieldEndTime.getText();
			
		
			if(jRadioButtonCourseType1.isSelected()){
				type = jRadioButtonCourseType1.getText();
			} else {
				type = jRadioButtonCourseType2.getText() +" : " + days;
			}

			String description = "Type: " + type + "\n" + "Starttijd: " +
					startTime + "\n" +
					"Eindtijd: " + endTime + "\n" +
					jTextAreaDescription.getText();
			subscription.setDescription(description);
						

			if (jRadioButtonMale.isSelected()) {
				subscription.setGender(true);
			} else if (jRadioButtonFemale.isSelected()) {
				subscription.setGender(false);
			} else {
				//Don't set the gender.
			}
			
			if (jComboBoxAgeGroup.getSelectedIndex() == 1) {
				subscription.setMinimumAge(0);
				subscription.setMaximumAge(16);
			} else if (jComboBoxAgeGroup.getSelectedIndex() == 2) {
				subscription.setMinimumAge(16);
				subscription.setMaximumAge(18);
			} else if (jComboBoxAgeGroup.getSelectedIndex() == 3) {
				subscription.setMinimumAge(18);
				subscription.setMaximumAge(65);
			} else if (jComboBoxAgeGroup.getSelectedIndex() == 4) {
				subscription.setMinimumAge(65);
				subscription.setMaximumAge(150);
			}
			
			String startDate = jTextFieldStartDate.getText();
			helper.Datetime datetime = new helper.Datetime(startDate + " 00:00:00");	
			subscription.setStartDate(datetime.timestamp());
			
			String endDate = jTextFieldStartDate.getText();
			helper.Datetime datetime2 = new helper.Datetime(endDate + " 00:00:00");	
			subscription.setEndDate(datetime2.timestamp());
			
			double price = Double.parseDouble(jTextFieldPrice.getText());
			subscription.setPrice(price);
					
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCourseName = new javax.swing.JLabel();
        jLabelCourseType = new javax.swing.JLabel();
        jLabelCourseStartDate = new javax.swing.JLabel();
        jLabelCourseEndDate = new javax.swing.JLabel();
        jLabelCourseStart = new javax.swing.JLabel();
        jLabelCourseEnd = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelFocusGroup = new javax.swing.JLabel();
        jLabelAgeGroup = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jRadioButtonCourseType1 = new javax.swing.JRadioButton();
        jRadioButtonCourseType2 = new javax.swing.JRadioButton();
        jCheckBoxMonday = new javax.swing.JCheckBox();
        jCheckBoxTuesday = new javax.swing.JCheckBox();
        jCheckBoxWednesday = new javax.swing.JCheckBox();
        jCheckBoxThursday = new javax.swing.JCheckBox();
        jCheckBoxFriday = new javax.swing.JCheckBox();
        jCheckBoxSaturday = new javax.swing.JCheckBox();
        jCheckBoxSunday = new javax.swing.JCheckBox();
        jTextFieldStartDate = new javax.swing.JTextField();
        jTextFieldEndDate = new javax.swing.JTextField();
        jTextFieldStartTime = new javax.swing.JTextField();
        jTextFieldEndTime = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonMixed = new javax.swing.JRadioButton();
        jComboBoxAgeGroup = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jTextFieldCourseName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();

        jLabelCourseName.setText("Naam *");

        jLabelCourseType.setText("Type");

        jLabelCourseStartDate.setText("Start datum");

        jLabelCourseEndDate.setText("Eind datum");

        jLabelCourseStart.setText("Begin cursus");

        jLabelCourseEnd.setText("Eind cursus");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 16));
        jLabel7.setText("Omschrijving");

        jLabelFocusGroup.setText("Doelgroep");

        jLabelAgeGroup.setText("Leeftijds groep");

        jLabelDescription.setText("Omschrijving");

        jRadioButtonCourseType1.setText("Los");

        jRadioButtonCourseType2.setText("Dagelijks");
        jRadioButtonCourseType2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonCourseType2StateChanged(evt);
            }
        });

        jCheckBoxMonday.setText("Ma");

        jCheckBoxTuesday.setText("Di");

        jCheckBoxWednesday.setText("Wo");

        jCheckBoxThursday.setText("Do");

        jCheckBoxFriday.setText("Vr");

        jCheckBoxSaturday.setText("Za");

        jCheckBoxSunday.setText("Zo");

        jRadioButtonMale.setText("Man");

        jRadioButtonFemale.setText("Vrouw");

        jRadioButtonMixed.setText("Gecombineerd");

        jComboBoxAgeGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16));
        jLabel1.setText("Cursus Aanmaken");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSave.setText("Opslaan");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Prijs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCourseType)
                            .addComponent(jLabelCourseName)
                            .addComponent(jLabelCourseStartDate)
                            .addComponent(jLabelCourseEndDate)
                            .addComponent(jLabelCourseStart)
                            .addComponent(jLabelCourseEnd))
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonCourseType2)
                            .addComponent(jRadioButtonCourseType1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jCheckBoxMonday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxTuesday))
                                    .addComponent(jTextFieldEndTime, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldStartTime, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxWednesday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxThursday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxFriday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxSaturday)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBoxSunday))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(13, 13, 13))))
                            .addComponent(jTextFieldCourseName))))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(653, Short.MAX_VALUE)
                .addComponent(jButtonSave)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription)
                    .addComponent(jLabelAgeGroup)
                    .addComponent(jLabelFocusGroup)
                    .addComponent(jLabel7))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMixed))
                    .addComponent(jComboBoxAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(694, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseName)
                    .addComponent(jTextFieldCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourseType)
                    .addComponent(jRadioButtonCourseType1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCourseType2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMonday)
                    .addComponent(jCheckBoxTuesday)
                    .addComponent(jCheckBoxWednesday)
                    .addComponent(jCheckBoxThursday)
                    .addComponent(jCheckBoxFriday)
                    .addComponent(jCheckBoxSaturday)
                    .addComponent(jCheckBoxSunday))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCourseStartDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCourseEndDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCourseStart))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCourseEnd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale)
                    .addComponent(jRadioButtonMixed)
                    .addComponent(jLabelFocusGroup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAgeGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAgeGroup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSave))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jRadioButtonCourseType2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonCourseType2StateChanged
		//When the RadioButton's state is chaged go to selectionCheck
		selectionCheck();

	}//GEN-LAST:event_jRadioButtonCourseType2StateChanged

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		getDays();
		System.out.println(days);
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
		// TODO add your handling code here:
		setSubscriptionData();
		subscription.create();
		
		Application.getInstance().showPanel(new view.barmedewerker.CoursesOverview());
		
		
	}//GEN-LAST:event_jButtonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxFriday;
    private javax.swing.JCheckBox jCheckBoxMonday;
    private javax.swing.JCheckBox jCheckBoxSaturday;
    private javax.swing.JCheckBox jCheckBoxSunday;
    private javax.swing.JCheckBox jCheckBoxThursday;
    private javax.swing.JCheckBox jCheckBoxTuesday;
    private javax.swing.JCheckBox jCheckBoxWednesday;
    private javax.swing.JComboBox jComboBoxAgeGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAgeGroup;
    private javax.swing.JLabel jLabelCourseEnd;
    private javax.swing.JLabel jLabelCourseEndDate;
    private javax.swing.JLabel jLabelCourseName;
    private javax.swing.JLabel jLabelCourseStart;
    private javax.swing.JLabel jLabelCourseStartDate;
    private javax.swing.JLabel jLabelCourseType;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelFocusGroup;
    private javax.swing.JRadioButton jRadioButtonCourseType1;
    private javax.swing.JRadioButton jRadioButtonCourseType2;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JRadioButton jRadioButtonMixed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldCourseName;
    private javax.swing.JTextField jTextFieldEndDate;
    private javax.swing.JTextField jTextFieldEndTime;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextFieldStartDate;
    private javax.swing.JTextField jTextFieldStartTime;
    // End of variables declaration//GEN-END:variables
}
