/*
 * CourseEdit.java
 *
 * Created on May 18, 2012, 8:53:21 PM
 */
package view.admin;

import java.util.Date;
import javax.swing.ButtonGroup;
import main.Application;
import model.Subscription;
import view.popups.SuccessPopup;

/**
 * This is the view for editing a course
 * @author mennowolvers
 */
public class CourseEdit extends javax.swing.JPanel {

	String days;
	String type;
	Subscription subscription;

	/** Creates new form CourseAdd */
	public CourseEdit( int id ) {
		initComponents();
		
		this.subscription = new Subscription( id );

		jComboBoxAgeGroup.removeAllItems();
		jComboBoxAgeGroup.addItem("< 16");
		jComboBoxAgeGroup.addItem("16 - 18");
		jComboBoxAgeGroup.addItem("18 - 65");
		jComboBoxAgeGroup.addItem("65 +");

		ButtonGroup buttongroupType = new ButtonGroup();
		buttongroupType.add(jRadioButtonCourseType1);
		buttongroupType.add(jRadioButtonCourseType2);

		ButtonGroup buttongroupGender = new ButtonGroup();
		buttongroupGender.add(jRadioButtonMale);
		buttongroupGender.add(jRadioButtonFemale);
		buttongroupGender.add(jRadioButtonMixed);
		
		this.populate();

	}
	
	public void populate()
	{
		jTextFieldCourseName.setText( this.subscription.getTitle() );
		
		if( this.subscription.getType() == 'd' )
			jRadioButtonCourseType2.setSelected(true);
		else
			jRadioButtonCourseType1.setSelected(true);
		
		jTextFieldStartTime.setText( String.valueOf( this.subscription.getStartTime() ) );
		jTextFieldEndTime.setText( String.valueOf( this.subscription.getEndTime() ) );
		jTextFieldStartDate.setText( String.valueOf( this.subscription.getStartDate() ) );
		jTextFieldEndDate.setText( String.valueOf( this.subscription.getEndDate() ) );
		
		if( this.subscription.getGender() == 'm' )
			jRadioButtonMale.setSelected(true);
		else if( this.subscription.getGender() == 'f' )
			jRadioButtonMale.setSelected(true);
		else
			jRadioButtonMixed.setSelected(true);
		
		jTextFieldPrice.setText( String.valueOf( this.subscription.getPrice() ) );
		
		if( this.subscription.getMaximumAge() <= 16 )
			jComboBoxAgeGroup.setSelectedIndex(0);
		else if( this.subscription.getMaximumAge() <= 18 )
			jComboBoxAgeGroup.setSelectedIndex(1);
		else if( this.subscription.getMaximumAge() <= 65 )
			jComboBoxAgeGroup.setSelectedIndex(2);
		else if( this.subscription.getMaximumAge() <= 150 )
			jComboBoxAgeGroup.setSelectedIndex(3);
		
		jTextAreaDescription.setText( this.subscription.getDescription() );
	}

	public void setSubscriptionData() {
		
			
			String name = jTextFieldCourseName.getText();
			subscription.setTitle(name);
			
			String startTime = jTextFieldStartTime.getText();
			String endTime = jTextFieldEndTime.getText();
			
		
			if(jRadioButtonCourseType1.isSelected()){
				type = jRadioButtonCourseType1.getText();
			} else {
				type = jRadioButtonCourseType2.getText() +" : " + days;
			}

			String description = "Type: " + type + "\n" + "Starttijd: " +
					startTime + "\n" +
					"Eindtijd: " + endTime + "\n" +
					jTextAreaDescription.getText();
			subscription.setDescription(description);
						

			if (jRadioButtonMale.isSelected()) {
				subscription.setGender('m');
			} else if (jRadioButtonFemale.isSelected()) {
				subscription.setGender('f');
			} else {
				//Don't set the gender.
			}
			
			if (jComboBoxAgeGroup.getSelectedIndex() == 1) {
				subscription.setMinimumAge(0);
				subscription.setMaximumAge(16);
			} else if (jComboBoxAgeGroup.getSelectedIndex() == 2) {
				subscription.setMinimumAge(16);
				subscription.setMaximumAge(18);
			} else if (jComboBoxAgeGroup.getSelectedIndex() == 3) {
				subscription.setMinimumAge(18);
				subscription.setMaximumAge(65);
			} else if (jComboBoxAgeGroup.getSelectedIndex() == 4) {
				subscription.setMinimumAge(65);
				subscription.setMaximumAge(150);
			}
			
			String jStartDate = jTextFieldStartDate.getText();
			//Date startDate = new Date();
			//helper.DateTime datetime = new helper.Datetime(startDate);	
			//subscription.setStartDate(datetime.format("yyyy-mm-dd"));
			
			//String endDate = jTextFieldStartDate.getText();
			//helper.Datetime datetime2 = new helper.Datetime(endDate);	
			//subscription.setEndDate(datetime2.timestamp());
			
			double price = Double.parseDouble(jTextFieldPrice.getText());
			subscription.setPrice(price);
					
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabelCourseName = new javax.swing.JLabel();
                jLabelCourseType = new javax.swing.JLabel();
                jLabelCourseStartDate = new javax.swing.JLabel();
                jLabelCourseEndDate = new javax.swing.JLabel();
                jLabelCourseStart = new javax.swing.JLabel();
                jLabelCourseEnd = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabelFocusGroup = new javax.swing.JLabel();
                jLabelAgeGroup = new javax.swing.JLabel();
                jLabelDescription = new javax.swing.JLabel();
                jRadioButtonCourseType1 = new javax.swing.JRadioButton();
                jRadioButtonCourseType2 = new javax.swing.JRadioButton();
                jTextFieldStartDate = new javax.swing.JTextField();
                jTextFieldEndDate = new javax.swing.JTextField();
                jTextFieldStartTime = new javax.swing.JTextField();
                jTextFieldEndTime = new javax.swing.JTextField();
                jRadioButtonMale = new javax.swing.JRadioButton();
                jRadioButtonFemale = new javax.swing.JRadioButton();
                jRadioButtonMixed = new javax.swing.JRadioButton();
                jComboBoxAgeGroup = new javax.swing.JComboBox();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextAreaDescription = new javax.swing.JTextArea();
                jTextFieldCourseName = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                jButtonSave = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jTextFieldPrice = new javax.swing.JTextField();
                jCheckBoxMonday = new javax.swing.JCheckBox();
                jCheckBoxTuesday = new javax.swing.JCheckBox();
                jCheckBoxThursday = new javax.swing.JCheckBox();
                jCheckBoxWednesday = new javax.swing.JCheckBox();
                jCheckBoxFriday = new javax.swing.JCheckBox();
                jCheckBoxSaturday = new javax.swing.JCheckBox();
                jCheckBoxSunday = new javax.swing.JCheckBox();

                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabelCourseName.setText("Naam *");
                add(jLabelCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, -1, -1));

                jLabelCourseType.setText("Type");
                add(jLabelCourseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 65, -1, -1));

                jLabelCourseStartDate.setText("Start datum");
                add(jLabelCourseStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, -1, -1));

                jLabelCourseEndDate.setText("Eind datum");
                add(jLabelCourseEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 178, -1, -1));

                jLabelCourseStart.setText("Begin cursus");
                add(jLabelCourseStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 214, -1, -1));

                jLabelCourseEnd.setText("Eind cursus");
                add(jLabelCourseEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

                jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 16));
                jLabel7.setText("Omschrijving");
                add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 316, -1, -1));

                jLabelFocusGroup.setText("Doelgroep");
                add(jLabelFocusGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 344, -1, -1));

                jLabelAgeGroup.setText("Leeftijds groep");
                add(jLabelAgeGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 374, -1, -1));

                jLabelDescription.setText("Omschrijving");
                add(jLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

                jRadioButtonCourseType1.setText("Los");
                add(jRadioButtonCourseType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 61, -1, -1));

                jRadioButtonCourseType2.setText("Dagelijks");
                jRadioButtonCourseType2.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                jRadioButtonCourseType2StateChanged(evt);
                        }
                });
                jRadioButtonCourseType2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRadioButtonCourseType2ActionPerformed(evt);
                        }
                });
                add(jRadioButtonCourseType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 85, -1, -1));
                add(jTextFieldStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 136, 150, -1));
                add(jTextFieldEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 172, 150, -1));
                add(jTextFieldStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 208, 150, -1));
                add(jTextFieldEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 244, 150, -1));

                jRadioButtonMale.setText("Man");
                add(jRadioButtonMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

                jRadioButtonFemale.setText("Vrouw");
                add(jRadioButtonFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

                jRadioButtonMixed.setText("Gecombineerd");
                add(jRadioButtonMixed, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

                jComboBoxAgeGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                add(jComboBoxAgeGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

                jTextAreaDescription.setColumns(20);
                jTextAreaDescription.setRows(5);
                jScrollPane1.setViewportView(jTextAreaDescription);

                add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 520, -1));
                add(jTextFieldCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 29, 340, -1));

                jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
                jLabel1.setText("Cursus wijzigen");
                add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                jButtonSave.setText("Opslaan");
                jButtonSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonSaveActionPerformed(evt);
                        }
                });
                add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

                jLabel2.setText("Prijs");
                add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 286, -1, -1));
                add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 280, 150, -1));

                jCheckBoxMonday.setText("Ma");
                jCheckBoxMonday.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCheckBoxMondayActionPerformed(evt);
                        }
                });
                add(jCheckBoxMonday, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 108, -1, -1));

                jCheckBoxTuesday.setText("Di");
                add(jCheckBoxTuesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 108, -1, -1));

                jCheckBoxThursday.setText("Do");
                add(jCheckBoxThursday, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 108, -1, -1));

                jCheckBoxWednesday.setText("Wo");
                add(jCheckBoxWednesday, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 108, -1, -1));

                jCheckBoxFriday.setText("Vr");
                add(jCheckBoxFriday, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 108, -1, -1));

                jCheckBoxSaturday.setText("Za");
                add(jCheckBoxSaturday, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 108, -1, -1));

                jCheckBoxSunday.setText("Zo");
                add(jCheckBoxSunday, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 108, -1, -1));
        }// </editor-fold>//GEN-END:initComponents

	private void jRadioButtonCourseType2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonCourseType2StateChanged
		//When the RadioButton's state is chaged go to selectionCheck

	}//GEN-LAST:event_jRadioButtonCourseType2StateChanged

	private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
		// TODO add your handling code here:
		setSubscriptionData();
		subscription.edit();
		
		Application.getInstance().showPanel(new view.barmedewerker.CoursesOverview());
		
		
	}//GEN-LAST:event_jButtonSaveActionPerformed

private void jRadioButtonCourseType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCourseType2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonCourseType2ActionPerformed

private void jCheckBoxMondayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMondayActionPerformed
		// TODO add your handling code here:
}//GEN-LAST:event_jCheckBoxMondayActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonSave;
        private javax.swing.JCheckBox jCheckBoxFriday;
        private javax.swing.JCheckBox jCheckBoxMonday;
        private javax.swing.JCheckBox jCheckBoxSaturday;
        private javax.swing.JCheckBox jCheckBoxSunday;
        private javax.swing.JCheckBox jCheckBoxThursday;
        private javax.swing.JCheckBox jCheckBoxTuesday;
        private javax.swing.JCheckBox jCheckBoxWednesday;
        private javax.swing.JComboBox jComboBoxAgeGroup;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabelAgeGroup;
        private javax.swing.JLabel jLabelCourseEnd;
        private javax.swing.JLabel jLabelCourseEndDate;
        private javax.swing.JLabel jLabelCourseName;
        private javax.swing.JLabel jLabelCourseStart;
        private javax.swing.JLabel jLabelCourseStartDate;
        private javax.swing.JLabel jLabelCourseType;
        private javax.swing.JLabel jLabelDescription;
        private javax.swing.JLabel jLabelFocusGroup;
        private javax.swing.JRadioButton jRadioButtonCourseType1;
        private javax.swing.JRadioButton jRadioButtonCourseType2;
        private javax.swing.JRadioButton jRadioButtonFemale;
        private javax.swing.JRadioButton jRadioButtonMale;
        private javax.swing.JRadioButton jRadioButtonMixed;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextArea jTextAreaDescription;
        private javax.swing.JTextField jTextFieldCourseName;
        private javax.swing.JTextField jTextFieldEndDate;
        private javax.swing.JTextField jTextFieldEndTime;
        private javax.swing.JTextField jTextFieldPrice;
        private javax.swing.JTextField jTextFieldStartDate;
        private javax.swing.JTextField jTextFieldStartTime;
        // End of variables declaration//GEN-END:variables
}
