/*
 * Dashboard.java
 *
 * Created on May 6, 2012, 3:13:00 PM
 */
package view.admin;

import helper.Datetime;
import helper.ExceptionHandler;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import main.Application;
import main.Session;
import model.Attendance;
import model.Enrollment;
import model.Purchase;
import model.User;
import view.popups.ErrorPopup;

/**
 *
 * @author Daan
 */
public class Dashboard extends javax.swing.JPanel {

	protected DefaultTableModel purchaseTableModel;
	protected DefaultTableModel enrollmentTableModel;
	private User sessionUser = Session.get().getLoggedInUser();
	private User user = new User();

	/**
	 * Creates new form Dashboard
	 */
	public Dashboard() {
		initComponents();

		purchaseTableModel = (DefaultTableModel) recentPayments.getModel();

		//disbale user elementes if no user has been found yet
		jLabelCustomerName.setVisible(false);
		userFoundPanel.setVisible(false);
		jLabelCustomerBirthdate.setVisible(false);
		jLabelCustomerGender.setVisible(false);
		checkinSuccessText.setVisible(false);
		checkinSuccessPanel.setVisible(false);
		userCourses.setVisible(false);

		updateLatestPurchase();
		updateTotalMembers();
		updateUserInfo();
	}

	private void updateUserInfo() {
		this.jLabelFullname.setText(sessionUser.getFullName());
	}

	private void updateTotalMembers() {

		this.totalMembers.setText(User.totalMembers() + " totaal inschrivingen");
	}

	private void updateLatestPurchase() {

		Purchase purchaseModel = new Purchase();

		purchaseTableModel.setRowCount(0);

		// Secondly, fill it with all users
		ArrayList<Purchase> purchases = purchaseModel.readLastPurchase(20);

		for (Purchase purchase : purchases) {
			purchaseTableModel.addRow(purchase.getTableRowObjects());
		}

	}

	public void searchUser() {

		try {

			int id = Integer.parseInt(userSearchField.getText());

			user.readUser(id);

			jLabelCustomerName.setVisible(true);
			userFoundPanel.setVisible(true);


			if (user.getId() > 0) {

				jLabelCustomerBirthdate.setVisible(true);
				jLabelCustomerGender.setVisible(true);
				userCourses.setVisible(true);

				int userId = user.getId();
				// Set the label
				jLabelCustomerName.setText(user.getFullName());

				Datetime datetime = new Datetime(user.getBirthdate());
				jLabelCustomerBirthdate.setText(datetime.format("dd-MM-yyyy"));

				if (user.getGender()) {
					jLabelCustomerGender.setText("Man");
				} else {
					jLabelCustomerGender.setText("Vrouw");
				}
				userCheckin.setEnabled(true);
				addUserCoursesToComboBox(userId);

			} else {
				jLabelCustomerName.setText("Gebru2iker niet gevonden");
			}
		} catch (Exception ex) {
			ExceptionHandler.handle(ex, ExceptionHandler.TYPE_SYSTEM_ERROR);
		}



	}

	public void addUserCoursesToComboBox(int userId) {
		userCourses.removeAllItems();

		ArrayList<Enrollment> enrollments = Enrollment.readByUserId(userId);

		for (Enrollment enrollment : enrollments) {

			Object lol = new Object();

			userCourses.addItem(enrollment);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        recentPayments = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFullname = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        userSearchField = new javax.swing.JTextField();
        jLabelFullname1 = new javax.swing.JLabel();
        jButtonSearchUser = new javax.swing.JButton();
        userFoundPanel = new javax.swing.JPanel();
        jLabelCustomerName = new javax.swing.JLabel();
        jLabelCustomerBirthdate = new javax.swing.JLabel();
        jLabelCustomerGender = new javax.swing.JLabel();
        userCourses = new javax.swing.JComboBox();
        userCheckin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        checkinSuccessPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelFullname2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        checkinSuccessText = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        access = new javax.swing.JButton();
        jLabelFullname3 = new javax.swing.JLabel();
        totalMembers = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(831, 501));

        recentPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Datum", "Prijs", "Product", "Betaald"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recentPayments);
        recentPayments.getColumnModel().getColumn(0).setResizable(false);
        recentPayments.getColumnModel().getColumn(1).setResizable(false);
        recentPayments.getColumnModel().getColumn(2).setResizable(false);
        recentPayments.getColumnModel().getColumn(3).setResizable(false);

        jPanel2.setBackground(new java.awt.Color(242, 241, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Welkom terug, ");

        jLabelFullname.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelFullname.setText("jLabelFullname");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(37, 37, 37)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelFullname)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabelFullname))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Aangemeld voor cursussen");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jLabel3)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Recente activiteiten");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(242, 241, 240));

        userSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchFieldActionPerformed(evt);
            }
        });

        jLabelFullname1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelFullname1.setText("Gebruiker inchecken");

        jButtonSearchUser.setText("Zoeken");
        jButtonSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUserActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(userSearchField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonSearchUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLabelFullname1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(13, 13, 13)
                .add(jLabelFullname1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(userSearchField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonSearchUser))
                .add(23, 23, 23))
        );

        userFoundPanel.setBackground(new java.awt.Color(242, 241, 240));

        jLabelCustomerName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabelCustomerName.setText("gebruiker");

        jLabelCustomerBirthdate.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabelCustomerBirthdate.setText("21-05-2012");

        jLabelCustomerGender.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabelCustomerGender.setText("gender");

        userCourses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCoursesActionPerformed(evt);
            }
        });
        userCourses.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                userCoursesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        userCheckin.setText("Inchecken");
        userCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserCheckinActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout userFoundPanelLayout = new org.jdesktop.layout.GroupLayout(userFoundPanel);
        userFoundPanel.setLayout(userFoundPanelLayout);
        userFoundPanelLayout.setHorizontalGroup(
            userFoundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
            .add(userFoundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(userFoundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(userFoundPanelLayout.createSequentialGroup()
                        .add(jLabelCustomerBirthdate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelCustomerGender, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 130, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, userFoundPanelLayout.createSequentialGroup()
                        .add(userFoundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(userFoundPanelLayout.createSequentialGroup()
                                .add(jLabelCustomerName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .add(37, 37, 37))
                            .add(userFoundPanelLayout.createSequentialGroup()
                                .add(userCourses, 0, 241, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                        .add(userCheckin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        userFoundPanelLayout.setVerticalGroup(
            userFoundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(userFoundPanelLayout.createSequentialGroup()
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabelCustomerName)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(userFoundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelCustomerBirthdate)
                    .add(jLabelCustomerGender))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(userFoundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(userCourses, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(userCheckin))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        checkinSuccessPanel.setBackground(new java.awt.Color(242, 241, 240));

        jLabelFullname2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelFullname2.setText("Succesvol ingecheckt");

        checkinSuccessText.setBackground(new java.awt.Color(242, 241, 240));
        checkinSuccessText.setBorder(null);
        checkinSuccessText.setEditable(false);
        jScrollPane2.setViewportView(checkinSuccessText);

        org.jdesktop.layout.GroupLayout checkinSuccessPanelLayout = new org.jdesktop.layout.GroupLayout(checkinSuccessPanel);
        checkinSuccessPanel.setLayout(checkinSuccessPanelLayout);
        checkinSuccessPanelLayout.setHorizontalGroup(
            checkinSuccessPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
            .add(checkinSuccessPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(checkinSuccessPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(checkinSuccessPanelLayout.createSequentialGroup()
                        .add(jLabelFullname2)
                        .add(0, 165, Short.MAX_VALUE))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );
        checkinSuccessPanelLayout.setVerticalGroup(
            checkinSuccessPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(checkinSuccessPanelLayout.createSequentialGroup()
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(2, 2, 2)
                .add(jLabelFullname2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Statistieken");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel4)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(242, 241, 240));

        access.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/activity_monitor_chart.png"))); // NOI18N
        access.setText("Open statistieken");
        access.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        access.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessActionPerformed(evt);
            }
        });

        jLabelFullname3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelFullname3.setText("Aantal gebruikers:");

        totalMembers.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        totalMembers.setText("<#>");

        jLabel5.setText("<html>Om deze statistieken te<br>kunnen openen dient het<br>programma Microsoft Access<br>geïnstalleerd te zijn.</html>");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(access, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(jLabelFullname3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(totalMembers)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelFullname3)
                    .add(totalMembers))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(access, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(userFoundPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(checkinSuccessPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(userFoundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(checkinSuccessPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void userSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchFieldActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_userSearchFieldActionPerformed

	private void jButtonUserCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserCheckinActionPerformed
		// TODO add your handling code here:

		userCheckin.setEnabled(false);

		Enrollment selectedEnrollment = (Enrollment) userCourses.getSelectedItem();
		Attendance attendance = new Attendance();
		attendance.setEnrollmentId(selectedEnrollment.getId());
		if (attendance.create()) {

			Datetime currentDate = new Datetime();

			String success = user.getFullName() + " is succesvol ingecheckt in de vestiging " + selectedEnrollment.getBranch().getCity() + " op " + currentDate.format("dd MM yyyy") + " om " + currentDate.format("hh:mm");
			checkinSuccessPanel.setVisible(true);
			checkinSuccessText.setVisible(true);
			checkinSuccessText.setText(success);
		}
	}//GEN-LAST:event_jButtonUserCheckinActionPerformed

	private void jButtonSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUserActionPerformed
		// TODO add your handling code here:
		searchUser();
	}//GEN-LAST:event_jButtonSearchUserActionPerformed

	private void userCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCoursesActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_userCoursesActionPerformed

	private void userCoursesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userCoursesCaretPositionChanged
		// TODO add your handling code here:
	}//GEN-LAST:event_userCoursesCaretPositionChanged

	private void accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessActionPerformed
		File accessFile = new File("src/resources/PASDB.accdb");
		if (Desktop.isDesktopSupported()) {
			try {
				Desktop.getDesktop().open(accessFile);
			} catch (IOException ex) {
				// no application registered for Access files
				Application.getInstance().showPopup(new ErrorPopup(
						"Microsoft Access is niet geïnstalleerd"));
			}
		}
	}//GEN-LAST:event_accessActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton access;
    private javax.swing.JPanel checkinSuccessPanel;
    private javax.swing.JTextPane checkinSuccessText;
    private javax.swing.JButton jButtonSearchUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCustomerBirthdate;
    private javax.swing.JLabel jLabelCustomerGender;
    private javax.swing.JLabel jLabelCustomerName;
    private javax.swing.JLabel jLabelFullname;
    private javax.swing.JLabel jLabelFullname1;
    private javax.swing.JLabel jLabelFullname2;
    private javax.swing.JLabel jLabelFullname3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable recentPayments;
    private javax.swing.JLabel totalMembers;
    private javax.swing.JButton userCheckin;
    private javax.swing.JComboBox userCourses;
    private javax.swing.JPanel userFoundPanel;
    private javax.swing.JTextField userSearchField;
    // End of variables declaration//GEN-END:variables
}
