/*
 * ErrorPopup.java
 *
 * Created on May 13, 2012, 2:37:50 PM
 */
package view.popups;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import main.Application;

/**
 *
 * @author Daan
 */
abstract public class DetailPopup extends javax.swing.JPanel {

	/**
	 * The alpha transparant background for popups
	 */
	protected JPanel popupBackground;
	public JButton jButtonConfirm;
	public JButton jButtonClose;

	/**
	 * Creates new form ErrorPopup
	 *
	 * @param message The message to show
	 */
	public DetailPopup(String message) {
		super();
		initComponents();

		// Convert private buttons to public buttons
		jButtonConfirm = jButtonConfirmPopup;
		jButtonClose = jButtonClosePopup;

		// Fix newlines
		message = "<html>" + message + "</html>";
		message = message.replaceAll("(\n)", "<br>");

		// Set the message
		jLabelMessage.setText(message);

		// Update the size according to the message	
		Dimension textSize = this.jLabelMessage.getPreferredSize();
		Dimension popupSize = new Dimension(textSize.width + 100, textSize.height + 170);

		// Give the close button focus
		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				jButtonConfirmPopup.requestFocusInWindow();
			}
		});

	}

	/**
	 * Set the color of this popup.
	 *
	 * @param color The color for the title and the border
	 */
	protected void setColor(Color color) {

		// Set the border color...
		Border newBorder = new LineBorder(color, 3, false);
		this.jPanelBorders.setBorder(newBorder);

		// ...and the title color
		jLabelTitle.setForeground(color);
	}

	/**
	 * Set the title of this popup.
	 *
	 * @param title The title for this popup.
	 */
	protected void setTitle(String title) {
		jLabelTitle.setText(title);
	}

	/**
	 * Close this popup
	 */
	public void close() {
		Application.getInstance().closePopup();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBorders = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonConfirmPopup = new javax.swing.JButton();
        jButtonClosePopup = new javax.swing.JButton();

        setOpaque(false);

        jPanelBorders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabelTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitle.setText("<TITEL>");

        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelMessage.setText("<bericht komt hier>");
        jLabelMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonConfirmPopup.setText("Ok");
        jButtonConfirmPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmPopupActionPerformed(evt);
            }
        });
        jButtonConfirmPopup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonConfirmPopupKeyReleased(evt);
            }
        });
        jPanel1.add(jButtonConfirmPopup, new java.awt.GridBagConstraints());

        jButtonClosePopup.setText("Annuleren");
        jButtonClosePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClosePopupActionPerformed(evt);
            }
        });
        jButtonClosePopup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonClosePopupKeyReleased(evt);
            }
        });
        jPanel1.add(jButtonClosePopup, new java.awt.GridBagConstraints());

        org.jdesktop.layout.GroupLayout jPanelBordersLayout = new org.jdesktop.layout.GroupLayout(jPanelBorders);
        jPanelBorders.setLayout(jPanelBordersLayout);
        jPanelBordersLayout.setHorizontalGroup(
            jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBordersLayout.createSequentialGroup()
                .add(jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBordersLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .add(jPanelBordersLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .add(jLabelTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelBordersLayout.setVerticalGroup(
            jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBordersLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelTitle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBorders, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBorders, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonConfirmPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmPopupActionPerformed
		this.close();
	}//GEN-LAST:event_jButtonConfirmPopupActionPerformed

	private void jButtonConfirmPopupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonConfirmPopupKeyReleased
		// If this is an enter, check the login
		// The KeyCode for an enter is 10
		if (evt.getKeyCode() == 10) {
			this.close();
		}
	}//GEN-LAST:event_jButtonConfirmPopupKeyReleased

private void jButtonClosePopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClosePopupActionPerformed
	this.close();
}//GEN-LAST:event_jButtonClosePopupActionPerformed

private void jButtonClosePopupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonClosePopupKeyReleased
// TODO add your handling code here:
}//GEN-LAST:event_jButtonClosePopupKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClosePopup;
    private javax.swing.JButton jButtonConfirmPopup;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBorders;
    // End of variables declaration//GEN-END:variables
}
