/*
 * InvoicePopup.java
 *
 * Created on May 31, 2012, 11:55:03 PM
 */
package view.popups;

import helper.Datetime;
import helper.PdfCreator;
import helper.db.Model;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import main.Application;
import model.Enrollment;
import model.Invoice;
import model.Purchase;
import model.User;

/**
 *
 * @author Daan
 */
public class InvoicePopup extends javax.swing.JPanel {

	private final Invoice invoice;

	/**
	 * Creates new form InvoicePopup
	 * 
	 * @param invoice The invoice to show
	 */
	public InvoicePopup(Invoice invoice) {

		this.invoice = invoice;

		initComponents();
		fillData();

		// Give the close button focus
		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				jButtonClose.requestFocusInWindow();
			}
		});
	}

	private void fillData() {

		// Update user data
		User user = invoice.getUser();
		Datetime birthdate = new Datetime(user.getBirthdate());
		jLabelUserId.setText(Integer.toString(user.getId()));
		jLabelUserName.setText(user.getFullName());
		jLabelUserBirthdate.setText(birthdate.format("yyyy-MM-dd"));

		// Update invoice data
		Datetime invoiceDate = new Datetime(invoice.getInvoiceDate());
		jLabelInvoiceId.setText(Integer.toString(invoice.getId()));
		jLabelInvoiceDate.setText(invoiceDate.format("yyyy-MM-dd"));
		jLabelPrice.setText(String.format("%.2f", invoice.getAmount()));

		// Get the Enrollments and Products
		ArrayList<Enrollment> enrollments = invoice.getEnrollments();
		ArrayList<Purchase> purchases = invoice.getPurchases();

		// Add the enrollments
		for (int i = 0; i < enrollments.size(); i++) {
			
			Enrollment enrollment = enrollments.get(i);
			
			// Description
			JLabel description = new JLabel(enrollment.getSubscription().getTitle());
			jPanelDescription.add(description);
			
			// Count is always 1 for enrollments
			JLabel count = new JLabel("1");
			jPanelCount.add(count);
			
			// Price
			JLabel price = new JLabel(String.format("%.2f", enrollment.getSubscription().getPrice()));
			jPanelPrice.add(price);
		}
		
		// Add the purchases
		for (int i = 0; i < purchases.size(); i++) {
			
			Purchase purchase = purchases.get(i);
			
			// Description
			JLabel description = new JLabel(purchase.getProduct().getName());
			jPanelDescription.add(description);
			
			// Count is always 1 for enrollments
			JLabel count = new JLabel(Integer.toString(purchase.getQuantity()));
			jPanelCount.add(count);
			
			// Price
			JLabel price = new JLabel(String.format("%.2f", purchase.getPrice()));
			jPanelPrice.add(price);
		}
		
		this.revalidate();
		this.repaint();
	}

	/**
	 * Close this popup
	 */
	public void close() {
		Application.getInstance().closePopup();
	}

	/**
	 * Open as PDF
	 */
	public void openPdf() {

		// Hide the buttons
		jButtonShowPdf.setVisible(false);
		jButtonClose.setVisible(false);

		// Create and open the pdf
		new PdfCreator(this);

		// Show the buttons again
		jButtonShowPdf.setVisible(true);
		jButtonClose.setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelDescription = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelCount = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelPrice = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelUserId = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelUserBirthdate = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelInvoiceDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelInvoiceId = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();
        jButtonShowPdf = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18));
        jLabel1.setText("Fitshape Sportscholen");

        jPanelDescription.setOpaque(false);
        jPanelDescription.setLayout(new javax.swing.BoxLayout(jPanelDescription, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel2.setText("Omschrijving");
        jPanelDescription.add(jLabel2);

        jPanelCount.setOpaque(false);
        jPanelCount.setLayout(new javax.swing.BoxLayout(jPanelCount, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel3.setText("Aantal");
        jPanelCount.add(jLabel3);

        jPanelPrice.setOpaque(false);
        jPanelPrice.setLayout(new javax.swing.BoxLayout(jPanelPrice, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel4.setText("Prijs");
        jPanelPrice.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel5.setText("Totaal:");

        jLabelPrice.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabelPrice.setText("<##>");

        jPanel4.setOpaque(false);

        jLabel10.setText("Geboortedatum:");

        jLabel9.setText("Naam:");

        jLabel8.setText("Lidnummer:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel7.setText("Gegevens lid");

        jLabelUserId.setText("<lidnummer>");

        jLabelUserName.setText("<naam>");

        jLabelUserBirthdate.setText("<geboortedatum>");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(jLabel8)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelUserId)
                            .add(jLabelUserName)
                            .add(jLabelUserBirthdate))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabelUserId))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jLabelUserName))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jLabelUserBirthdate))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel5.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        jLabel11.setText("Gegevens factuur");

        jLabel12.setText("Factuurdatum:");

        jLabelInvoiceDate.setText("<factuurdatum>");

        jLabel6.setText("Factuurnummer:");

        jLabelInvoiceId.setText("<factuurnummer>");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel11)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel12))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelInvoiceDate)
                            .add(jLabelInvoiceId))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jLabelInvoiceId))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jLabelInvoiceDate))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jButtonClose.setText("Sluiten");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jButtonClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonCloseKeyReleased(evt);
            }
        });

        jButtonShowPdf.setText("Open als PDF");
        jButtonShowPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowPdfActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(jPanelDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .add(18, 18, 18)
                                .add(jPanelCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18))
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(438, 438, 438)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelPrice)
                            .add(jPanelPrice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(jButtonShowPdf)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonClose)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelCount, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanelPrice, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabelPrice))
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonShowPdf)
                    .add(jButtonClose))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {jPanelCount, jPanelDescription, jPanelPrice}, org.jdesktop.layout.GroupLayout.VERTICAL);

    }// </editor-fold>//GEN-END:initComponents

	private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
		this.close();
	}//GEN-LAST:event_jButtonCloseActionPerformed

	private void jButtonCloseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCloseKeyReleased
		// If this is an enter, check the login
		// The KeyCode for an enter is 10
		if (evt.getKeyCode() == 10) {
			this.close();
		}
	}//GEN-LAST:event_jButtonCloseKeyReleased

	private void jButtonShowPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowPdfActionPerformed
		this.openPdf();
	}//GEN-LAST:event_jButtonShowPdfActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonShowPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInvoiceDate;
    private javax.swing.JLabel jLabelInvoiceId;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelUserBirthdate;
    private javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelCount;
    private javax.swing.JPanel jPanelDescription;
    private javax.swing.JPanel jPanelPrice;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
