/*
 * ErrorPopup.java
 *
 * Created on May 13, 2012, 2:37:50 PM
 */
package view.popups;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import main.Application;

/**
 *
 * @author Daan
 */
public class SuccessPopup extends javax.swing.JPanel {

	public static final int TYPE_NORMAL = 0;
	public static final int TYPE_ERROR = 1;
	public static final int TYPE_NOTICE = 2;
	public static final int TYPE_SUCCESS = 3;
	protected static Color[] colors = new Color[4];
	/**
	 * The alpha transparant background for popups
	 */
	protected JPanel popupBackground;

	/**
	 * Creates new form ErrorPopup
	 * 
	 * @param message The message to show
	 */
	public SuccessPopup(String message) {
		super();
		initComponents();
		
		// Fix newlines
		message = "<html>" + message + "</html>";
		message.replaceAll("\n", "<br>");
		
		// Set the message
		jLabelMessage.setText(message);
		
		// Give the close button focus
		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				jButtonClosePopup.requestFocusInWindow();
			}
		});
		
	}
	
	/**
	 * Close this popup
	 */
	public void close() {
		Application.getInstance().closePopup();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBorders = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonClosePopup = new javax.swing.JButton();

        setOpaque(false);

        jPanelBorders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0), 3));

        jLabelTitle.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelTitle.setForeground(new java.awt.Color(51, 204, 0));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("GESLAAGD");

        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setText("<bericht komt hier>");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonClosePopup.setText("OK");
        jButtonClosePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClosePopupActionPerformed(evt);
            }
        });
        jButtonClosePopup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonClosePopupKeyReleased(evt);
            }
        });
        jPanel1.add(jButtonClosePopup, new java.awt.GridBagConstraints());

        org.jdesktop.layout.GroupLayout jPanelBordersLayout = new org.jdesktop.layout.GroupLayout(jPanelBorders);
        jPanelBorders.setLayout(jPanelBordersLayout);
        jPanelBordersLayout.setHorizontalGroup(
            jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBordersLayout.createSequentialGroup()
                .add(jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBordersLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                    .add(jPanelBordersLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .add(jLabelTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelBordersLayout.setVerticalGroup(
            jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBordersLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelTitle)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBorders, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBorders, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonClosePopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClosePopupActionPerformed
		this.close();
	}//GEN-LAST:event_jButtonClosePopupActionPerformed

	private void jButtonClosePopupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonClosePopupKeyReleased
		// If this is an enter, check the login
		// The KeyCode for an enter is 10
		if (evt.getKeyCode() == 10) {
			this.close();
		}
	}//GEN-LAST:event_jButtonClosePopupKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClosePopup;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBorders;
    // End of variables declaration//GEN-END:variables
}
