/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Header.java
 *
 * Created on May 6, 2012, 8:44:06 PM
 */
package view;

/**
 *
 * @author vm
 */
public class Footer extends javax.swing.JPanel {

    /** Creates new form Header */
    public Footer() {
        initComponents();
        
    }
	

	
	

	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneHeader = new javax.swing.JLayeredPane();
        header = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 20));
        setMinimumSize(new java.awt.Dimension(1000, 20));
        setPreferredSize(new java.awt.Dimension(1000, 20));
        setSize(new java.awt.Dimension(1000, 20));
        setLayout(new java.awt.BorderLayout());

        jLayeredPaneHeader.setMaximumSize(new java.awt.Dimension(1000, 20));
        jLayeredPaneHeader.setMinimumSize(new java.awt.Dimension(1000, 20));
        jLayeredPaneHeader.setPreferredSize(new java.awt.Dimension(1000, 20));
        jLayeredPaneHeader.setRequestFocusEnabled(false);
        jLayeredPaneHeader.setSize(new java.awt.Dimension(1000, 20));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/footer.png"))); // NOI18N
        header.setBounds(0, 0, 1000, 20);
        jLayeredPaneHeader.add(header, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPaneHeader, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header;
    private javax.swing.JLayeredPane jLayeredPaneHeader;
    // End of variables declaration//GEN-END:variables

}
