/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Header.java
 *
 * Created on May 6, 2012, 8:44:06 PM
 */
package view;

import main.Session;
import model.User;

/**
 *
 * @author vm
 */
public class Header extends javax.swing.JPanel {

    /** Creates new form Header */
    public Header() {
        initComponents();
    }
	
	/**
	 * Set the visibility of the user info at the right side
	 * 
	 * @param visible The visibility of the user info
	 */
	public void showUserInfo(boolean visible) {
		this.jLayeredPaneUser.setVisible(visible);
	}
	
	/**
	 * Update the user info
	 */
	public void updateUserInfo() {
		
		// Check if a user is logged in
		User user = Session.get().getLoggedInUser();
		
		if(user == null) {
			// There is no logged in user, so hide the user info
			this.showUserInfo(false);
		}
		else {
			// Update the user info to the currently logged in user
			this.jLabelUsername.setText(user.getFullName());
			// And show the user info
			this.showUserInfo(true);
		}
		
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPaneHeader = new javax.swing.JLayeredPane();
        jLayeredPaneUser = new javax.swing.JLayeredPane();
        userIcon = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        header = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 50));
        setMinimumSize(new java.awt.Dimension(1000, 50));
        setPreferredSize(new java.awt.Dimension(1000, 50));
        setLayout(new java.awt.BorderLayout());

        jLayeredPaneHeader.setMaximumSize(new java.awt.Dimension(1000, 50));
        jLayeredPaneHeader.setMinimumSize(new java.awt.Dimension(1000, 50));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/user_32.png"))); // NOI18N
        userIcon.setBounds(360, 10, 32, 32);
        jLayeredPaneUser.add(userIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelUsername.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsername.setText("<gebruikersnaam>");
        jLabelUsername.setBounds(21, 7, 330, 18);
        jLayeredPaneUser.add(jLabelUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogout.setText("<html><u>uitloggen</u></html>");
        jLabelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });
        jLabelLogout.setBounds(220, 25, 130, 14);
        jLayeredPaneUser.add(jLabelLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPaneUser.setBounds(600, 0, 400, 50);
        jLayeredPaneHeader.add(jLayeredPaneUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/header.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(1008, 50));
        header.setMinimumSize(new java.awt.Dimension(1008, 50));
        header.setBounds(0, 0, 1000, 50);
        jLayeredPaneHeader.add(header, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPaneHeader, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
		Session.get().logOut();
	}//GEN-LAST:event_jLabelLogoutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLayeredPane jLayeredPaneHeader;
    private javax.swing.JLayeredPane jLayeredPaneUser;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables

}
