/*
 * Login.java
 *
 * Created on May 7, 2012, 7:26:22 PM
 */
package view;

import main.Session;

/**
 *
 * @author vm
 */
public class Login extends javax.swing.JPanel {

	/** Creates new form Login */
	public Login() {
		initComponents();
	}
	
	/**
	 * Check if the given username and password are correct
	 */
	protected void checkLogin() {
		
		String username = jTextFieldUsername.getText();
		String password = new String(jPasswordField.getPassword());
		
		// Check if all fields are given
		if (username.equals("") || password.equals("")) {
			Popup popup = new Popup();
			popup.showError("U heeft uw gebruikersnaam of wachtwoord niet ingevuld.");
			return;
		}
		
		if(Session.get().logIn(username, password)) {
			// Login succesful, reset input fields
			jTextFieldUsername.setText(null);
			jPasswordField.setText(null);
		}
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCenterredWrapper = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1LoginWrapper = new javax.swing.JPanel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonLogIn = new javax.swing.JButton();
        jPanelForgotPassword = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18));
        jLabel6.setText("Inloggen");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(560, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jLabelDescription.setText("<html>Bent u al een abbonnee van de sportschool FitShape? Log dan in met uw gebruikersnaam en wachtwoord.</html>");

        jLabelUsername.setText("Gebruikersnaam");

        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyReleased(evt);
            }
        });

        jLabelPassword.setText("Wachtwoord");

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyReleased(evt);
            }
        });

        jButtonLogIn.setText("Inloggen");
        jButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogInActionPerformed(evt);
            }
        });
        jButtonLogIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonLogInKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1LoginWrapperLayout = new javax.swing.GroupLayout(jPanel1LoginWrapper);
        jPanel1LoginWrapper.setLayout(jPanel1LoginWrapperLayout);
        jPanel1LoginWrapperLayout.setHorizontalGroup(
            jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1LoginWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1LoginWrapperLayout.createSequentialGroup()
                        .addGroup(jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsername)
                            .addComponent(jLabelPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1LoginWrapperLayout.setVerticalGroup(
            jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1LoginWrapperLayout.createSequentialGroup()
                .addGroup(jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1LoginWrapperLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1LoginWrapperLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1LoginWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("<html><u>Wachtwoord vergeten?</u></html>");

        jLabel4.setText("<html>Bent u uw wachtwoord vergeten? Loop dan even naar een van onze medewerkers</html>");

        javax.swing.GroupLayout jPanelForgotPasswordLayout = new javax.swing.GroupLayout(jPanelForgotPassword);
        jPanelForgotPassword.setLayout(jPanelForgotPasswordLayout);
        jPanelForgotPasswordLayout.setHorizontalGroup(
            jPanelForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForgotPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelForgotPasswordLayout.setVerticalGroup(
            jPanelForgotPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelForgotPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCenterredWrapperLayout = new javax.swing.GroupLayout(jPanelCenterredWrapper);
        jPanelCenterredWrapper.setLayout(jPanelCenterredWrapperLayout);
        jPanelCenterredWrapperLayout.setHorizontalGroup(
            jPanelCenterredWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterredWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterredWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCenterredWrapperLayout.createSequentialGroup()
                        .addComponent(jPanel1LoginWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelForgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCenterredWrapperLayout.setVerticalGroup(
            jPanelCenterredWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterredWrapperLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterredWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelForgotPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1LoginWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        add(jPanelCenterredWrapper, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogInActionPerformed
		checkLogin();
    }//GEN-LAST:event_jButtonLogInActionPerformed

	private void jTextFieldUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyReleased
		// If this is an enter, check the login
		// The KeyCode for an enter is 10
		if(evt.getKeyCode() == 10) {
			checkLogin();
		}
	}//GEN-LAST:event_jTextFieldUsernameKeyReleased

	private void jPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyReleased
		// If this is an enter, check the login
		// The KeyCode for an enter is 10
		if(evt.getKeyCode() == 10) {
			checkLogin();
		}
	}//GEN-LAST:event_jPasswordFieldKeyReleased

	private void jButtonLogInKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLogInKeyReleased
		// If this is an enter, check the login
		// The KeyCode for an enter is 10
		if(evt.getKeyCode() == 10) {
			checkLogin();
		}
	}//GEN-LAST:event_jButtonLogInKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1LoginWrapper;
    private javax.swing.JPanel jPanelCenterredWrapper;
    private javax.swing.JPanel jPanelForgotPassword;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
