/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Popup.java
 *
 * Created on May 13, 2012, 2:37:50 PM
 */
package view;

import main.Application;
import main.Main;

/**
 *
 * @author Daan
 */
public class Popup extends javax.swing.JPanel {

	/** Creates new form Popup */
	public Popup() {
		initComponents();
	}
	
	/**
	 * Change the message of the popup
	 * 
	 * @param message The new message to show
	 */
	public void setMessage(String message) {
		this.jLabelMessage.setText(message);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBorders = new javax.swing.JPanel();
        jLabelFoutmelding = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonClosePopup = new javax.swing.JButton();

        setOpaque(false);

        jPanelBorders.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));

        jLabelFoutmelding.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabelFoutmelding.setForeground(new java.awt.Color(255, 0, 0));
        jLabelFoutmelding.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoutmelding.setText("FOUTMELDING");

        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setText("<foutmelding bericht komt hier>");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonClosePopup.setText("OK");
        jButtonClosePopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClosePopupActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClosePopup, new java.awt.GridBagConstraints());

        org.jdesktop.layout.GroupLayout jPanelBordersLayout = new org.jdesktop.layout.GroupLayout(jPanelBorders);
        jPanelBorders.setLayout(jPanelBordersLayout);
        jPanelBordersLayout.setHorizontalGroup(
            jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBordersLayout.createSequentialGroup()
                .add(jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelBordersLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                    .add(jPanelBordersLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                            .add(jLabelFoutmelding, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelBordersLayout.setVerticalGroup(
            jPanelBordersLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelBordersLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabelFoutmelding)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBorders, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelBorders, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jButtonClosePopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClosePopupActionPerformed
		Application application = Main.getApplication();
		application.hidePopup();
	}//GEN-LAST:event_jButtonClosePopupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClosePopup;
    private javax.swing.JLabel jLabelFoutmelding;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBorders;
    // End of variables declaration//GEN-END:variables
}
