/**
 * CourseInfo.java
 *
 * Created on May 10, 2012, 10:21:26 PM
 */
package view.barmedewerker;

import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import main.Application;
import main.ExceptionHandler;
import model.Enrollment;
import model.Subscription;
import model.User;
import view.popups.SuccessPopup;

/**
 * This is the view to inquiry detailed information about a course.
 *
 * @author mennowolvers
 */
public class CourseInfo extends javax.swing.JPanel {
	private Subscription subscription;
	private DefaultTableModel model;
	private ListSelectionModel row;
	private int userId;

	/** Creates new form CourseInfo */
	public CourseInfo() {
		initComponents();
	}
	
	public CourseInfo( int subscriptionId ) {
		initComponents();
		
		this.subscription = new Subscription( subscriptionId );
		this.model = (DefaultTableModel)jTableUsers.getModel();
		
		this.render();
	}
	
	public void render() {
		jLabelName.setText( this.subscription.getTitle() );
		jLabelGender.setText( "Man" );
		jLabelAge.setText( String.valueOf( this.subscription.getMinimumAge() ) );
		jLabelDays.setText( "Maandag, Woensdag" );
		jLabelDuration.setText( String.valueOf( this.subscription.getStartTime() ) + " - " + String.valueOf( this.subscription.getEndTime() ) );
		jLabelDescription.setText( this.subscription.getDescription() );
		
		// Enrollments
		ArrayList<User> users = Enrollment.readBySubscriptionId( this.subscription.getId() );
		
		for( User user : users ) {
			if( user.getFullName() != "" && user.getFirstname() != null ) {
				this.model.insertRow( 0, new Object[]{ user.getId(), user.getFullName() } );
			}
		}
		
		// Make a selection listener
		this.row = jTableUsers.getSelectionModel();
		this.row.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
		
	}
	
	public void searchUser() {
		// Search a user and return a result
		// TODO: search by name, etc.
		User user = new User();
		
		try {
			int id = Integer.parseInt(jTextId.getText());
			user.readUser(id);
			if(user.getId() > 0){
				this.userId = user.getId();
				// Set the label
				jLabelUser.setText(user.getFullName());
			}
		} catch (Exception ex) {
			ExceptionHandler.handle(ex, ExceptionHandler.TYPE_SYSTEM_ERROR);
		}
		
		

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabelDescription = new javax.swing.JLabel();
                jLabelDuration = new javax.swing.JLabel();
                jLabelDays = new javax.swing.JLabel();
                jLabelGender = new javax.swing.JLabel();
                jLabelName = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                jLabel6 = new javax.swing.JLabel();
                jLabelAge = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jTextId = new javax.swing.JTextField();
                jBtnSearch = new javax.swing.JButton();
                jSeparator2 = new javax.swing.JSeparator();
                jLabelUser = new javax.swing.JLabel();
                jLabelBirthdate = new javax.swing.JLabel();
                jBtnSubmit = new javax.swing.JButton();
                jLabel8 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTableUsers = new javax.swing.JTable();

                jLabel1.setText("Naam");

                jLabel2.setText("Geslacht");

                jLabel3.setText("Duratie");

                jLabel4.setText("Dagen");

                jLabel5.setText("Omschrijving");

                jLabelDescription.setText("Omschrijving");
                jLabelDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

                jLabelDuration.setText("Duratie");

                jLabelDays.setText("Dagen");

                jLabelGender.setText("Geslacht");

                jLabelName.setText("Naam");

                jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

                jLabel6.setText("Leeftijdscategorie");

                jLabelAge.setText("Leeftijdscategorie");

                jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
                jLabel7.setText("Deelnemer");

                jTextId.setText("Klantnummer");

                jBtnSearch.setText("Zoeken");
                jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBtnSearchActionPerformed(evt);
                        }
                });

                jLabelUser.setFont(new java.awt.Font("Lucida Grande", 1, 13));
                jLabelUser.setText("Menno Wolvers");

                jLabelBirthdate.setText("18-09-1991");

                jBtnSubmit.setText("Aanmelden");
                jBtnSubmit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jBtnSubmitActionPerformed(evt);
                        }
                });

                jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
                jLabel8.setText("Deelnemers");

                jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Klantnr", "Deelnemer"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane1.setViewportView(jTableUsers);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel6))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabelAge)
                                                                        .addComponent(jLabelName)
                                                                        .addComponent(jLabelGender)
                                                                        .addComponent(jLabelDays)
                                                                        .addComponent(jLabelDuration))
                                                                .addGap(67, 67, 67))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel7)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jBtnSearch)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabelBirthdate)
                                                                        .addComponent(jLabelUser))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                                                                .addComponent(jBtnSubmit)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel2)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabelName)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelGender)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelDays)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabelDuration)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabelAge))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jBtnSearch))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabelUser)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabelBirthdate))
                                                        .addComponent(jBtnSubmit)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
	this.searchUser();
}//GEN-LAST:event_jBtnSearchActionPerformed

private void jBtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubmitActionPerformed
	Enrollment enrollment = new Enrollment();
	enrollment.subscribe( this.subscription.getId(), this.userId );
	
	
	User user = new User();
	user.readUser( this.userId );
	
	this.model.insertRow( 0, new Object[] { user.getId(), user.getFullName() } );
	
	Application.getInstance().showPopup(new SuccessPopup("Deelnemer " + user.getFullName() + " is ingeschreven."));
}//GEN-LAST:event_jBtnSubmitActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jBtnSearch;
        private javax.swing.JButton jBtnSubmit;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabelAge;
        private javax.swing.JLabel jLabelBirthdate;
        private javax.swing.JLabel jLabelDays;
        private javax.swing.JLabel jLabelDescription;
        private javax.swing.JLabel jLabelDuration;
        private javax.swing.JLabel jLabelGender;
        private javax.swing.JLabel jLabelName;
        private javax.swing.JLabel jLabelUser;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JTable jTableUsers;
        private javax.swing.JTextField jTextId;
        // End of variables declaration//GEN-END:variables
}
